# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Peass with extracted node diff generator (intermedia workflow, replaced when nodeDiffGenerator has its first release

on:
  push:
    branches: [ extractNodeDiffGenerator ]
  workflow_dispatch:

jobs:
  build:
    strategy: 
        matrix:
          os: [ubuntu-latest, windows-latest] # no macos-latest since github actions always procudes EDTIMEOUT
          java: [ 1.8, 11, 17 ]
        fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }} OS ${{ matrix.os }} sample
    steps:
    - name: Set Git Property and output path
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          git config --system core.longpaths true
          echo %PATH%
          where mvn
          mvn -version
        fi
      shell: bash
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build Node Diff Generator
      run: |
         branch=main
         cd /home/runner/work/ && git clone -b $branch git@github.com:DaGeRe/nodeDiffGenerator.git && cd nodeDiffGenerator && echo "Branch: $branch" && git rev-parse HEAD && ./mvnw clean install -DskipTests
    - name: Build Peass all (for version compatibility check)
      run: ./mvnw -B package -DskipTests -P buildStarter --file pom.xml && ls ~/.m2/repository/ 
    - name: Build Peass dependency, measurement and analysis
      run: ./mvnw -B install --file pom.xml
    - name: Publish Test Report ${{ matrix.java }} OS ${{ matrix.os }}
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         check_name: Test Report ${{ matrix.java }} OS ${{ matrix.os }}
    - name: Upload Unit Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results (Java ${{ matrix.java }} OS ${{ matrix.os }})
        path: |
          dependency/target/surefire-reports/*
          measurement/target/surefire-reports/*
          analysis/target/surefire-reports/*
