# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Peass-JMH (PR)

on: [push, workflow_dispatch]

jobs:
  build:
    strategy: 
        matrix:
          os: [ubuntu-latest, windows-latest] # no macos-latest since github actions always procudes EDTIMEOUT
          java: [ 1.8, 11, 17, 21 ]
        fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }} OS ${{ matrix.os }} sample
    steps:
    - name: Set Git Property and output path
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          git config --system core.longpaths true
          echo %PATH%
          where mvn
          mvn -version
        fi
      shell: bash
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build Peass dependency, measurement and analysis
      run: ./mvnw -B install --file pom.xml -DskipTests && ls ~/.m2/repository/ && ls ~/.m2/repository/de/dagere/kopeme/kopeme-core
    - name: Build Peass-JMH
      run: cd peass-jmh && ../mvnw -B install --file pom.xml && cd ..
